services:
  otel-collector:
    command:
      - --config
      - /otel-config.yaml
    #image: otel/opentelemetry-collector-contrib:0.102.1
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    volumes:
      - /home/docker/opentelemetry/conf/otel-collector.yaml:/otel-config.yaml
    ports:
      - 0.0.0.0:1888:1888 # pprof extension
      - 0.0.0.0:8888:8888 # Prometheus metrics exposed by the Collector
      - 0.0.0.0:8889:8889 # Prometheus exporter metrics
      - 0.0.0.0:13133:13133 # health_check extension
      - 0.0.0.0:4317:4317 # OTLP gRPC receiver
      - 0.0.0.0:4318:4318 # OTLP http receiver
      - 0.0.0.0:55679:55679 # zpages extension
