version: '3'

services:
  tiktok-user:
    image: docker.io/library/otel-gin
    container_name: otel-gin
    restart: unless-stopped
    ports:
      - "30001:30001"
    # 需要挂载的路径
    #volumes:
      #-
    command: [ "/app/otel-gin" ]
