services:

  # RocketMQ Web控制台
  dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rmqui
    ports:
      - "8088:8080"
    networks:
      - rocketmq
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=rmqnamesrv:9876  # 配置 NameServer 地址
    depends_on:
      - namesrv
      - broker
      - proxy
    restart: always

  # NameServer 服务
  namesrv:
    image: apache/rocketmq:5.3.1
    container_name: rmqnamesrv
    ports:
      - "9876:9876"
    networks:
      - rocketmq
    environment:
      - JAVA_OPTS=-Duser.home=/opt
    command: sh mqnamesrv
    restart: always

  # Broker 服务
  broker:
    image: apache/rocketmq:5.3.1
    container_name: rmqbroker
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    networks:
      - rocketmq
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876  # 使用容器名称连接 NameServer
    volumes:
      - ./broker.conf:/home/rocketmq/rocketmq-5.3.1/conf/broker.conf
    depends_on:
      - namesrv
    command: sh mqbroker --enable-proxy -c /home/rocketmq/rocketmq-5.3.1/conf/broker.conf
    restart: always

  # RocketMQ 代理
  proxy:
    image: apache/rocketmq:5.3.1
    container_name: rmqproxy
    networks:
      - rocketmq
    depends_on:
      - broker
      - namesrv
    ports:
      - 8080:8080
      - 8081:8081
    restart: on-failure
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
    command: sh mqproxy

networks:
  rocketmq:
    driver: bridge
