version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - /home/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=msdnmm
      - POSTGRES_DB=root
    ports:
      - 5432:5432
