services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./conf:/usr/local/etc/redis
    command:
      - "redis-server"
      - "/usr/local/etc/redis/redis.conf"
